version: '3.3'
services:
  app1:
    build: .
    volumes:
    # fist dataset location
        - ./shinyApps/shinyApp_MouseOrganogenesis:/srv/shiny-server
    ports:
        - 3838:3838
  ####
  #Uncomment if you like to run more than one app in one go
  ####
  # app2:
  #   build: .
  #   volumes:
  #       - ./shinyApps/shinyApp_Porrello_scRNAhuman:/srv/shiny-server
  #   ports:
  #       - 3839:3838