version: '3.3'

services:
  app1:
    build: .
    volumes:
    # fist dataset location
        - ./apps/shinyApp_MouseOrganogenesis:/srv/shiny-server
    ports:
        - 3838:3838
  app2:
    build: .
    volumes:
        - ./apps/shinyApp_Porrello_scRNAhuman:/srv/shiny-server
    ports:
        - 3839:3838